apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Deploying Solr Operator on Kubernetes
name: solr-operator
version: 0.0.1
icon: "https://zop.dev/logo.png"
dependencies:
  - name: 'zookeeper-operator'
    version: 0.0.1
    repository: https://helm.zop.dev
    condition: zookeeper-operator.install
maintainers:
  - name: ZopDev
    url: zop.dev