apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: {{ .Values.httpPort}}
    {{- if and .Values.metricsPort (ne (int .Values.metricsPort) 0) }}
    - name: metrics-port
      port: 2121
      targetPort: {{ .Values.metricsPort}}
    {{- end }}
    {{- if .Values.servPort }}
    - name: {{ .Values.servPort.name | default "service-port" }}
      port: {{ .Values.servPort.port }}
      targetPort: {{ .Values.servPort.targetPort | default .Values.servPort.port }}
    {{- end }} 
    {{- range $k, $v := .Values.ports}}
    - name: {{ $k}}
      port: {{ $v }}
      targetPort: {{ $v }}
      {{- end }}
  selector:
    app: {{ .Values.name }}
  type: NodePort
---