apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: {{ .Values.httpPort}}
    {{- if and .Values.metricsPort (ne (int .Values.metricsPort) 0) }}
    - name: metrics-port
      port: 2121
      targetPort: {{ .Values.metricsPort}}
    {{- end }}
    {{- if kindIs "map" .Values.ports }}
    {{- range $k, $v := .Values.ports}}
    - name: {{ $k}}
      port: {{ $v }}
      targetPort: {{ $v }}
      {{- end }}
    {{- else if kindIs "slice" .Values.ports }}
      {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ .Values.name }}
  type: NodePort
---