{{- if and .Values.volumes .Values.volumes.pvc }}
{{- range $index, $service :=  .Values.volumes.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $service.claimName }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ $.Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .storage | default "5Gi" }}
---
{{- end }}
{{- end }}